name: Check

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint check
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint codebase
        run: npm run lint

  build_codebase:
    name: Build Codebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Codebase
        run: npm run build

  # build_storybook:
  #   name: Build Storybook
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Use Node.js 14
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 14.x
  #         cache: 'npm'

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Build Storybook
  #       run: npm run build:storybook

  commits:
    name: Conventional Commits
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webiny/action-conventional-commits@v1.0.5
